language: go

go:
- 1.8.x
- 1.9.x
- 1.10.x
- 1.11.x

before_install:
- wget -O dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
- chmod +x dep
- ./dep ensure -v

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
- bash <(curl -s https://codecov.io/bash) -t 9b203862-16a1-4e50-8cb6-c2bbb0fd0d92